name : Golang web example
on:  
    push:
          branches:
          - 'v1.0'
          tag:
          - 'latest'

jobs:
  ci:
     runs-on: ubuntu-latest
     permission:
        contents: write
     steps:
        - name: Checkout
          uses: actions/check@v4
