name: Golong web example
on:
  push:
    branches:
    - 'v1.0'
    tags:
    - 'latest'
    paths-ignore:
    - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    build:
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          force_push_tag: true
          message: "Lastest release"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          tag: "latest"
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN}}

      - name: Get Repository URL
        id: repo_url
        run: echo "::set-output name=url::git://github.com/${{ github.repository }}.git"

        # run: echo "::set-output name=url::https://github.com/${{ github.repository }}"
            
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload:  |
            {
              "text": "CICD Workshop by Li Jinglin",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Name:*\n Li Jinglin"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\n A0276822X"
                  }
                },
                {
                  "type": "section",
                  "block_id": "section789",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Email :*\n 1694572764@qq.com"
                    }
                  ]
                },
                {
                  "type": "section",
                  "block_id": "section790",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository :*\n ${{steps.repo_url.outputs.url}}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "block_id": "section791",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployment :*\n ${{ secrets.Deployment}}"
                    }
                  ]
                }
              ]
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          

        
          